[project]
name = "tradebot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "kafka-python>=2.2.15",
    "lxml>=6.1.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "python-dotenv>=1.1.1",
    "websocket-client>=1.8.0",
    "wikipedia>=1.4.0",
]
